server:
  port: 8080
#项目名称
spring:
  application:
    name: uIO
  profiles:
    active: dev
  banner:
    location: banner.txt
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: springboot
    password: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "Qwe!230528"
      timeout: 6000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
# Redis配置
