server:
  port: 8080
#项目名称
spring:
  application:
    name: uIO
  profiles:
    active: dev
  banner:
    location: banner.txt
#数据库配置
  datasource:
    url: jdbc:mysql://wsssfun.rwlb.rds.aliyuncs.com:3306/springboot?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: wsssfun
    password: Qwe!230528
    driver-class-name: com.mysql.cj.jdbc.Driver
#Redis配置
#  data:
#    redis:
#      database: 0
#      host: 117.72.10.41
#      port: 6379
#      timeout: 5000
#      password: qwe123
#      lettuce:
#        pool:
#          max-active: 32
#          max-wait: -1
#          max-idle: 16
#          min-idle: 8